baseurl: "https://enddi.cn/"
languageCode: "zh-cn"
title: "enddi"
theme: "hugo-ivy"
googleAnalytics: "UA-92894937-1"
disqusShortname: "enddi"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "分类"
      url: "/categories/"
      weight: 2
    - name: "标签"
      url: "/tags/"
      weight: 3
    - name: "关于"
      url: "/about/"
      weight: 4
    - name: "GitHub"
      url: "https://github.com/z2x"
      weight: 5

params:
  description: "Personal website of Yihui Xie; 谢益辉的个人网站"
  footer: "&copy; [Endi Zhu](/) 20016 - 2018"
  disqusURL: "https://enddi.cn"
  customJS: ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js"]
  githubContentURL: "https://github.com/z2x"
  twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
      img: "/images/logo.jpg"
      url: "/"
      alt: "enddi"
      tag: ""

  author:
    en: "Endi Zhu"
    cn: "朱恩迪"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false